title="Multi monitor"

[endpoint.1]
title="My Endpoint"
network_id=1
url="http://1.geth.testnet.golem.network:55555"
request_burst=5
token_holder="0xc596aee002ebe98345ce3f967631aaf79cfbdf41"
token_address="0x2036807B0B3aaf5b1858EE822D0e111fDdac7018"

[endpoint.2]
title="Matic mumbai"
network_id=80001
url="https://rpc-mumbai.matic.today/"
request_burst=5
token_holder="0xc596aee002ebe98345ce3f967631aaf79cfbdf41"
token_address="0x2036807B0B3aaf5b1858EE822D0e111fDdac7018"